# Site settings
title: seotory dev story
email: seotory437@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seotory.github.io" # the base hostname & protocol for your site
twitter_username: seotory
github_username:  seotory

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# post separator
excerpt_separator: <!--more-->

# highlighter settings
highlighter: pygments

# url change
permalink: /:categories/:title/

# collections
collections:
  solutions:
    output: false
    permalink: /solution/:categories/:title/

# paging
paginate: 3
paginate_path: "/list:num/"

# gems
gems: [jekyll-paginate]

