# Site settings
title: seotory dev story
email: seotory437@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seotory.github.io" # the base hostname & protocol for your site
twitter_username: seotory
github_username:  seotory

# url change
permalink: /:year/:month/:day/:title

# highlighter settings
# Build settings
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  parse_block_html: true

# post separator
excerpt_separator: <!--more-->

# CSS
sass:
  sass_dir: _sass


# collections
collections:
  solutions:
    output: false
    permalink: /solution/:categories/:title/

# paging
paginate: 3
paginate_path: "/list/:num/"

# gems
gems: [jekyll-paginate]

